name: ng2-pdf-viewer workflow
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: npm install and test
      run: |
        npm install
        npm test
